dist: trusty

language: python

python:
  - 2.7

env:
  - ANSIBLE_VERSION=2.4.6.0
  - ANSIBLE_VERSION=2.4.5.0
  - ANSIBLE_VERSION=2.4.4.0
  - ANSIBLE_VERSION=2.4.3.0
  - ANSIBLE_VERSION=2.4.2.0
  - ANSIBLE_VERSION=2.4.1.0
  # - ANSIBLE_VERSION=2.4.0.0
  - ANSIBLE_VERSION=2.3.2.0
  - ANSIBLE_VERSION=2.3.1.0
  - ANSIBLE_VERSION=2.3.0.0
  - ANSIBLE_VERSION=2.2.3.0
  - ANSIBLE_VERSION=2.2.2.0
  # - ANSIBLE_VERSION=2.2.1.0
  - ANSIBLE_VERSION=2.2.0.0
  # - ANSIBLE_VERSION=2.1.6.0
  # - ANSIBLE_VERSION=2.1.5.0
  # - ANSIBLE_VERSION=2.1.4.0
  # - ANSIBLE_VERSION=2.1.3.0
  # - ANSIBLE_VERSION=2.1.2.0
  # - ANSIBLE_VERSION=2.1.1.0
  # - ANSIBLE_VERSION=2.1.0.0
  # - ANSIBLE_VERSION=2.0.2.0
  # - ANSIBLE_VERSION=2.0.1.0
  # - ANSIBLE_VERSION=2.0.0.2
  # - ANSIBLE_VERSION=2.0.0.1
  # - ANSIBLE_VERSION=1.9.6
  # - ANSIBLE_VERSION=1.9.5
  # - ANSIBLE_VERSION=1.9.4

script:
  - pex -o ansible-$ANSIBLE_VERSION.pex -v ansible==$ANSIBLE_VERSION ansible-lint pycodestyle yamllint netaddr ara==0.14.5
  - PEX_SCRIPT=ansible-playbook ./ansible-$ANSIBLE_VERSION.pex --version

deploy:
  provider: releases
  api_key:
    secure: LzA0jBVI3iyG8Y4kyq4ZYfBcQK4gEzoTIYxim8qQBvjDcPpMgFqs2h2+/DUkpKwJgqcm6u4TI2a040WtWzG7uO70A6rpwEhg6DLeDXURIc64P5krxuFO/TRCPsReWJF1/xZe73164ECuW57r8td1AWRK5X96B/18R3YyIEzqn60S7VLm+CfVXW3Xj+qS92Dtg9g1sMioASOTXUoo840lfi2UD7zbOTyg6hGvXZV2MXMSSeY2int/McrkMgmiCl/QwRcKVr+dQQL5vyHIZrSDDKUCtUeBB5BgVfa3Agpby0qrPweN5c05cRK+LMueam41JQ01llP7QgFqldHqPSOn/0yo3FX8Cjt3auoGaL10thAdhV6aG6QQnqZs6wk+5OfMP1dsKjEnmT/TGOO0qPWg2jVLWwDnwZCNR/SpcUiGm9+5oqbZxfZajZrHGDsUkclCk5kPP1TOMfIKdm+O/SDlZaYwfHZ0UVbVE5O+15mI2afG80qyphu/9xybbvsMnh71jedrKMcN/ccGHhtX/AmLNX7di2I2mYpTy0kZ2I4pQtyLzXRwStKXIu+und18mQBvd4ulcLBcVkd4m5ZBXDcKDdskypi70dAY5j9B6OsLmEsbOW7tXhXll3pzRWMNlEeSPlBxAcFtagEkR0OHGJnzztutI72c5EDmloKDloDSOJU=
  file: ansible-*.pex
  file_glob: true
  on:
    repo: pdericson/ansible-pex
    tags: true
  skip_cleanup: true
